import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Button from "@/components/Button";
import TextInput from "@/components/TextInput";
import Checkbox from "@/components/Checkbox";
import DropdownPicker from "@/components/DropdownPicker";
import ProductCard from "@/components/ProductCard";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Product } from "@/types/Product";
import CatalogService from "@/services/CatalogService";

export default function Home() {
    const [products, setProducts] = useState<Array<Product>>([]);
    const [page, setPage] = useState<number>(1);
    const [pagesCount, setPagesCount] = useState<number>(0);

    useEffect(() => {
        fetchProducts();
    }, []);

    async function fetchProducts() {
        const catalogResponse = await CatalogService.getProducts({page: 1});
        setProducts(catalogResponse.data);
        setPagesCount(catalogResponse.pages);
    }

    async function loadMoreProducts() {
        const catalogResponse = await CatalogService.getProducts({page: page + 1});
        setPage(page + 1);
        setProducts([...products, ...catalogResponse.data]);
    }
    
    return (
        <>
        <Head>
            <title>495TRAFFIC</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.Home__root}>
            <div className={styles.header}>
                <img src="/main-banner.webp" alt="main_banner" />
            </div>
            <div className={styles.wrapper}>
                <div className={styles.head}>
                    <h1>ACCESSORIES</h1>
                    <DropdownPicker
                        placeholder="Sort by"
                        items={[
                            "Popularity",
                            "Novelty",
                            "In ascending order of price",
                            "In descending order of price"
                        ]}
                    />
                </div>

                <div className={styles.products_grid}>
                    {products.map((product, index) => {
                        return(
                            <ProductCard
                                product={product}
                                key={index}
                            />
                        );
                    })}
                </div>

                <div className={styles.load_more}>
                    <Button
                        label="load more"
                        tertiary
                        onClick={() => loadMoreProducts()}
                    />
                </div>
            </div>

            <div className={styles.archive_banner_container}>
                <img src="/archive-banner.webp" alt="archive_banner" />
                <div className={styles.fade} />
                <div className={styles.wrapper}>
                    <p className={styles.title}>ARCHIVE</p>
                    <Link href="/archive" style={{textDecoration: 'none'}}>
                    <Button
                        label="SEE MORE"
                        tertiary
                    /></Link>
                </div>
            </div>
        </div>
        </>
    );
}
