import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Button from "@/components/Button";
import TextInput from "@/components/TextInput";
import Checkbox from "@/components/Checkbox";
import DropdownPicker from "@/components/DropdownPicker";
import ProductCard from "@/components/ProductCard";

export default function Home() {
    return (
        <>
        <Head>
            <title>495TRAFFIC</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.Home__root}>
            <div className={styles.header}>
                <img 
                    src="/main-banner.webp"
                    alt="main_banner"
                />
            </div>
            <div className={styles.wrapper}>
                <div className={styles.head}>
                    <h1>ALL PRODUCTS</h1>
                    <DropdownPicker
                        placeholder="Sort by"
                        items={[
                            "Popularity",
                            "Novelty",
                            "In ascending order of price",
                            "In descending order of price"
                        ]}
                    />
                </div>

                <div className={styles.products_grid}>
                    <ProductCard/>
                    <ProductCard/>
                    <ProductCard/>
                    <ProductCard/>

                    <ProductCard/>
                    <ProductCard/>
                    <ProductCard/>
                    <ProductCard/>
                </div>

                <div className={styles.load_more}>
                    <Button
                        label="load more"
                        tertiary
                    />
                </div>
            </div>

            <div className={styles.archive_banner_container}>
                <img 
                    src="/archive-banner.webp"
                    alt="archive_banner"
                />
                <div className={styles.fade} />
                <div className={styles.wrapper}>
                    <p className={styles.title}>ARCHIVE</p>
                    <Button
                        label="SEE MORE"
                        tertiary
                    />
                </div>
            </div>
        </div>
        </>
    );
}
