import Head from "next/head";
import styles from "@/styles/Kit.module.scss";
import Button from "@/components/Button";
import TextInput from "@/components/TextInput";
import Checkbox from "@/components/Checkbox";
import DropdownPicker from "@/components/DropdownPicker";

export default function Home() {
    return (
        <>
        <Head>
            <title>495TRAFFIC</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.Kit__root}>
            <Button
                label="Buy now"
            />
            <Button
                label="Learn more"
                secondary
            />
            <Button
                label="Load more"
                tertiary
            />

            <TextInput
                placeholder="Name"
                required
            />
            <TextInput
                value="Some value"
            />
            <TextInput
                value=""
                placeholder="City"
                required
                hints={[
                    "Moscow",
                    "Saint-Petersburg",
                    "Novosibirsk",
                    "Yekaterinburg",
                    "Nizhny Novgorod",
                    "Kazan",
                    "Chelyabinsk",
                    "Samara",
                    "Omsk",
                    "Rostov-on-Don",
                    "Ufa",
                    "Krasnoyarsk",
                    "Voronezh"
                ]}
            />
            <TextInput
                value="Some Wrong value"
                errorMsg="This is an error message"
            />

            <Checkbox/>
            <Checkbox
                checked
            />

            <Checkbox
                label="I agree with the personal data processing policy"
            />
            <Checkbox
                label="I agree with the personal data processing policy"
                error
            />
            <Checkbox
                label="I agree with the personal data processing policy"
                checked
            />

            <DropdownPicker
                placeholder="Sort by"
                items={[
                    "Popularity",
                    "Novelty",
                    "In ascending order of price",
                    "In descending order of price"
                ]}
                value=""
                onChange={value => {}}
            />
        </div>
        </>
    );
}
